spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/wesports?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: helloworld
      filters: log4j,wall,mergeStat

# service version
wesports:
  service:
    version: 1.0.dev

# redis config
redis:
  host: 127.0.0.1
  port: 6379
  password: wesports

# Dubbo Config properties
dubbo:
  application:
    id: wesports-web-dev
    name: wesports-web-dev
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
# web port
server:
  port: 9999
# mysql



---
spring:
  profiles: uat

# service version
wesports:
  service:
    version: 1.0

# redis config
redis:
  host: 47.113.91.20
  port: 6379
  password: wesports

# Dubbo Config properties
dubbo:
  application:
    id: wesports-web
    name: wesports-web
  registry:
    protocol: zookeeper
    address: 106.52.54.67:2181
# web port
server:
  port: 9999
