spring:
  profiles:
    active: dev

---
spring:
  profiles: dev

  redis:
    host: 106.52.54.67
    port: 6379
    password: wesports
# service version
wesports:
  service:
    version: 1.0.dev.test

# redis config


# Dubbo Config properties
dubbo:
  application:
    id: wesportrs-web-dev
    name: wesportrs-web-dev
    qos-enable: false
  registry:
    protocol: zookeeper
    address: 106.52.54.67:2181
  provider:
    timeout: 300000

#  registry:
#    protocol: zookeeper
#    address: 106.52.54.67:2181

# web port
server:
  port: 9999

---
spring:
  profiles: uat

# service version
wesports:
  service:
    version: 1.0

# redis config
redis:
  host: 106.52.54.67
  port: 6379
  password: wesports

# Dubbo Config properties
dubbo:
  application:
    id: wesports-web
    name: wesports-web
    registry:
      protocol: zookeeper
      address: 106.52.54.67:2181
# web port
server:
  port: 9999
