spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/wesports?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: helloworld
      filters: log4j,wall,mergeStat
      driver-class-name: com.mysql.jdbc.Driver

# service version
wesports:
  service:
    version: 1.0.dev

# redis config
redis:
  host: 47.113.91.20
  port: 6379
  password: wesports

# Dubbo Config properties
dubbo:
  application:
    id: wesportrs-web-service-dev
    name: wesportrs-web-service-dev
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
  provider:
    timeout: 300000
# web port
server:
  port: 9999

---
spring:
  profiles: uat

# service version
wesports:
  service:
    version: 1.0

# redis config
redis:
  host: 47.113.91.20
  port: 6379
  password: wesports

# Dubbo Config properties
dubbo:
  application:
    id: wesports-web
    name: wesports-web
  registry:
    protocol: zookeeper
    address: 106.52.54.67:2181
# web port
server:
  port: 9999
