spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.52.54.67:3306/wesports?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Wesport2020@
# redis config
  redis:
    host: 106.52.54.67
    port: 6379
    password: wesports

# service version
wesports:
  service:
    version: 1.0.dev

# Dubbo Config properties
dubbo:
  application:
    id: wesports-service-dev
    name: wesports-service-dev
    qos-enable: false
  registry:
    protocol: zookeeper
    address: 106.52.54.67:2181
  protocol:
    name: dubbo
    port: 20882
  provider:
    timeout: 300000
# web port
server:
  port: 9990
# mysql



---
spring:
  profiles: uat

# redis config
  redis:
    host: 106.52.54.67
    port: 6379
    password: wesports
# service version
wesports:
  service:
    version: 1.0



# Dubbo Config properties
dubbo:
  application:
    id: wesports-service
    name: wesports-service
    qos-enable: false
  registry:
    protocol: zookeeper
    address: 106.52.54.67:2181
  protocol:
    name: dubbo
    port: 20882
  provider:
    timeout: 5000

#web port
server:
  port: 9990

